apiVersion: v1
kind: Namespace
metadata:
  name: semantick-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semantick-pod # Base POD name.
  namespace: semantick-system
spec:
  selector:
    matchLabels:
      app: semantick # Selector for POD name search.
  template:
    metadata:
      labels:
        app: semantick
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
        - name: semantick
          image: semantick-image
          ports:
          - name: semantick
            containerPort: 3000
          - name: semantick-debug
            containerPort: 4000
          readinessProbe: # readiness probes mark the service available to accept traffic.
            httpGet:
              path: /debug/readiness
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
            httpGet:
              path: /debug/liveness
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_PODNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_NAMESPACE_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KUBERNETES_NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: semantick-service
  namespace: semantick-system
spec:
  type: ClusterIP
  selector:
    app: semantick
  ports:
  - name: semantick-api
    port: 3000
    targetPort: semantick-api
  - name: semantick-debug
    port: 4000
    targetPort: semantick-debug 
