apiVersion: v1
kind: Namespace
metadata:
  name: semantick-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semantick-pod # Base POD name.
  namespace: semantick-system
spec:
  selector:
    matchLabels:
      app: semantick # Selector for POD name search.
  template:
    metadata:
      labels:
        app: semantick
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
        - name: semantick
          image: semantick-image
          ports:
          - name: semantick
            containerPort: 3000
          - name: semantick-debug
            containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: semantick-service
  namespace: semantick-system
spec:
  type: ClusterIP
  selector:
    app: semantick
  ports:
  - name: semantick-api
    port: 3000
    targetPort: semantick-api
  - name: semantick-debug
    port: 4000
    targetPort: semantick-debug 
