apiVersion: apps/v1
kind: Deployment
metadata:
  name: semantick-pod
  namespace: semantick-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: semantick
  template:
    metadata:
      labels:
        app: semantick
    spec:
      containers:
      - name: semantick
        resources:
          limits:
            cpu: "500m" # Up to 1/2 full core
          requests:
            cpu: "250m" # Use 1/4 full core
