apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/semantick-pod/
patchesStrategicMerge:
- ./kind-semantick-patch.yaml
images:
- name: semantick-image
  newName: semantick-amd64
  newTag: "2.0"
